void door_ramp(uint8_t sn3, int position, int speed, int ramp_up, int ramp_down) ;
void door_up_ramp( uint8_t sn3, int speed, int ramp_up, int ramp_down) ;
void door_down_ramp( uint8_t sn3, int speed, int ramp_up, int ramp_down) ;
void door_up( uint8_t sn3, int speed) ;
void door_down( uint8_t sn3, int speed) ;
void door_up_standard( uint8_t sn3) ;
void door_down_standard( uint8_t sn3);
void door_mi_up( uint8_t sn3, int speed) ;
void door_mi_down( uint8_t sn3, int speed) ;
void door_mi_up_standard( uint8_t sn3) ;
void door_mi_down_standard( uint8_t sn3) ;
void catch_dist(uint8_t *sn, uint8_t sn_sonar, uint8_t sn3, int speed, int distance);
void catch_ball(uint8_t *sn, uint8_t sn3, uint8_t sn_sonar,int speed);
void catch_ball_after_check(uint8_t *sn, uint8_t sn_sonar, uint8_t sn3,int speed);
int scan_angle_distance(uint8_t *sn, uint8_t sn_sonar, int speed, int angle, int distance);
int scan_angle_distance2(uint8_t *sn, uint8_t sn_sonar, int speed, int angle, int distance);
int is_it_the_ball(uint8_t *sn, uint8_t sn3, uint8_t sn_sonar, uint8_t sn_color, int speed, int distance);
void run_back_no_ball(uint8_t *sn, uint8_t sn_sonar, uint8_t sn3, int speed);
void door_up_down( uint8_t sn3, int speed );
void release_ball(uint8_t *sn, uint8_t sn_sonar, uint8_t sn3, int speed, int distance);
int scan (uint8_t *sn, uint8_t sn3, uint8_t sn_sonar, uint8_t sn_color,int speed_scan, int speed_catch, int limit_distance);
int scan2 (uint8_t *sn, uint8_t sn3, uint8_t sn_sonar, uint8_t sn_color,int speed_scan, int speed_catch, int limit_distance);
int catch_if_ball(uint8_t *sn, uint8_t sn3, uint8_t sn_sonar, uint8_t sn_color, int speed_catch, int distance_to_object, int limit_distance);
