void init();
void uninit (uint8_t *sn3, uint8_t *sn4);
void init_all(uint8_t *sn1, uint8_t *sn2, uint8_t *sn3, uint8_t *sn4, uint8_t *sn_sonar, uint8_t *sn_color, uint8_t *sn_compass, uint8_t *sn_gyro, uint8_t *sn, int *s);
void init_wheels(uint8_t *sn1, uint8_t *sn2, uint8_t *sn);
void init_door_or_catapult(uint8_t *sn3,int port);
void init_catapult(uint8_t *sn4);
void init_door(uint8_t *sn3);
void init_sonar(uint8_t *sn_sonar );
void init_gyro (uint8_t *sn_gyro );
void init_color(uint8_t *sn_color);
void init_compass(uint8_t *sn_compass);
void init_threads(uint8_t *sn, uint8_t *sn_compass, uint8_t *sn_gyro, int *s);
