void * thread_position(void *input);
void create_thread_position(uint8_t *sn);
void * thread_compass (void *input);
void * thread_gyro (void *input);
void create_thread_compass(uint8_t *sn_compass);
void create_thread_gyro(uint8_t *sn_gyro);
void * thread_print_coordinates ();
void create_thread_print_coordinates();
float get_robot_angle(int choice);
float get_robot_abs_angle();
float get_robot_rel_angle();
float get_robot_angle_gyro();
int get_x_position();
int get_y_position();
void print_robot_abs_angle();
void print_robot_rel_angle();
void print_robot_position();
void print_robot_coordinates();
void create_threads(uint8_t *sn, uint8_t *sn_compass, uint8_t *sn_gyro);
