void * thread_position(void *input);
void create_thread_position(uint8_t *sn);
void * thread_angle(void *input);
void create_thread_angle(uint8_t *sn_compass);
void * thread_print_coordinates ();
void create_thread_print_coordinates();
float get_robot_angle(int choice);
float get_robot_abs_angle();
float get_robot_rel_angle();
int get_x_position();
int get_y_position();
void print_robot_abs_angle();
void print_robot_rel_angle();
void print_robot_position();
void print_robot_coordinates();
void create_threads(uint8_t *sn, uint8_t *sn_compass);
